# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/airline_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Phani@123.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Keep this to 'validate' or 'none' since you already created your tables in Workbench
spring.jpa.hibernate.ddl-auto=validate